### ISSUE TITLE
Release project to a public maven repository

### ISSUE THREAD

**Issue by meehaws** [gravity9-tech/mongo-cse#30] opened 2024-01-04 07:44 UTC

**Comment by piotr-bugara-gravity9** [comment] 2024-01-04 11:31
@meehaws Duplicate ot  https://github.com/gravity9-tech/mongocdc/issues/5

**Comment by PiotrGravity** [comment] 2024-02-06 11:30
Duplicate of #5

**Comment by BartekGravity** [comment] 2024-05-07 09:56
Closing as duplicate

**Closed by BartekGravity** 2024-05-07 09:56 UTC
